### PR TITLE
Upgraded to Java 11 and added Discovery Service

### PR DESCRIPTION
**Pull request by rickhui**
Dexter, please take a look. If it's ok, tell me which integration test I should add the Service Discovery module.

### CODE REVIEW

**Comment by dexterchan** [comment]
Shall we keep DiscoveryServiceStatic?
Now DiscoveryService now depends on AWS dynamoDB.
If nodebeam depends on DiscoveryService, it will depends on AWS dynamoDB as well.....
If you restore "TreeQueryDiscoveryServiceStatic", I will accept it to integration stream.
thanks

**Review by dexterchan — CHANGES_REQUESTED** [review]
Please keep "TreeQueryDiscoveryServiceStatic"... otherwise nodebeam will depends on AWS dynamoDB library as well.

**Comment by dexterchan** [comment]
why do we check in this binary?
TreeQueryDiscoveryService/src/test/resources/libs/libsqlite4java-osx.dylib

**Comment by rickhui** [comment]
> why do we check in this binary?
> TreeQueryDiscoveryService/src/test/resources/libs/libsqlite4java-osx.dylib

**Comment by rickhui** [comment]
> why do we check in this binary?
> TreeQueryDiscoveryService/src/test/resources/libs/libsqlite4java-osx.dylib

because they are the prerequisite libs for com.amazonaws:DynamoDBLocal...normally, it can be downloaded through gradle, but somehow it cannot. So I did a workaround here.

**Pull request closed without merging**
